[2025-03-07T10:43:35.512+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [queued]>
[2025-03-07T10:43:35.520+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [queued]>
[2025-03-07T10:43:35.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-03-07T10:43:35.530+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2025-03-07 10:43:34.575230+00:00
[2025-03-07T10:43:35.536+0000] {standard_task_runner.py:57} INFO - Started process 279 to run task
[2025-03-07T10:43:35.538+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2025-03-07T10:43:34.575230+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpk4r_hx3m']
[2025-03-07T10:43:35.540+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_postgres_table
[2025-03-07T10:43:35.577+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [running]> on host 93934f8e361f
[2025-03-07T10:43:35.640+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T10:43:34.575230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T10:43:34.575230+00:00'
[2025-03-07T10:43:35.641+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-03-07T10:43:35.656+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2025-03-07T10:43:35.660+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20250307T104334, start_date=20250307T104335, end_date=20250307T104335
[2025-03-07T10:43:35.671+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 279)
[2025-03-07T10:43:35.710+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-07T10:43:35.729+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
