[2025-03-07T10:48:36.239+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [queued]>
[2025-03-07T10:48:36.247+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [queued]>
[2025-03-07T10:48:36.247+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2025-03-07T10:48:36.259+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2025-03-07 10:43:34.575230+00:00
[2025-03-07T10:48:36.263+0000] {standard_task_runner.py:57} INFO - Started process 768 to run task
[2025-03-07T10:48:36.266+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2025-03-07T10:43:34.575230+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpwn0qt4wr']
[2025-03-07T10:48:36.268+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask create_postgres_table
[2025-03-07T10:48:36.316+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T10:43:34.575230+00:00 [running]> on host 93934f8e361f
[2025-03-07T10:48:36.397+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T10:43:34.575230+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T10:43:34.575230+00:00'
[2025-03-07T10:48:36.398+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-03-07T10:48:36.404+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T10:48:36.412+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T10:48:36.414+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-03-07T10:48:36.427+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20250307T104334, start_date=20250307T104836, end_date=20250307T104836
[2025-03-07T10:48:36.443+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task create_postgres_table (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 768)
[2025-03-07T10:48:36.478+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-07T10:48:36.505+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
