[2025-03-07T11:05:14.256+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:05:13.690220+00:00 [queued]>
[2025-03-07T11:05:14.261+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:05:13.690220+00:00 [queued]>
[2025-03-07T11:05:14.261+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-03-07T11:05:14.271+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2025-03-07 11:05:13.690220+00:00
[2025-03-07T11:05:14.275+0000] {standard_task_runner.py:57} INFO - Started process 1246 to run task
[2025-03-07T11:05:14.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2025-03-07T11:05:13.690220+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmp8zz3s2d3']
[2025-03-07T11:05:14.279+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask create_postgres_table
[2025-03-07T11:05:14.326+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:05:13.690220+00:00 [running]> on host 5588030d4cfa
[2025-03-07T11:05:14.404+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T11:05:13.690220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T11:05:13.690220+00:00'
[2025-03-07T11:05:14.405+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-03-07T11:05:14.421+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T11:05:14.436+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T11:05:14.498+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2025-03-07T11:05:14.515+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20250307T110513, start_date=20250307T110514, end_date=20250307T110514
[2025-03-07T11:05:14.533+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task create_postgres_table (could not translate host name "host.docker.internal" to address: Name or service not known
; 1246)
[2025-03-07T11:05:14.569+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-07T11:05:14.599+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
