[2025-03-07T11:45:10.423+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:35:07.723429+00:00 [queued]>
[2025-03-07T11:45:10.435+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:35:07.723429+00:00 [queued]>
[2025-03-07T11:45:10.436+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2025-03-07T11:45:10.449+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2025-03-07 11:35:07.723429+00:00
[2025-03-07T11:45:10.453+0000] {standard_task_runner.py:57} INFO - Started process 1797 to run task
[2025-03-07T11:45:10.456+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'manual__2025-03-07T11:35:07.723429+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpv4tk7cz8']
[2025-03-07T11:45:10.458+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask create_postgres_table
[2025-03-07T11:45:10.502+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table manual__2025-03-07T11:35:07.723429+00:00 [running]> on host 5837dac536a6
[2025-03-07T11:45:10.584+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T11:35:07.723429+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T11:35:07.723429+00:00'
[2025-03-07T11:45:10.586+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-03-07T11:45:10.598+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T11:45:10.607+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-07T11:45:10.608+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-03-07T11:45:10.614+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20250307T113507, start_date=20250307T114510, end_date=20250307T114510
[2025-03-07T11:45:10.625+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task create_postgres_table (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 1797)
[2025-03-07T11:45:10.668+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-07T11:45:10.698+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
